#% text_encoding = iso8859_1
##-----------------------------------------------------------------------------------------------
## What3Words Smallworld GE Implementation
## Copyright (C) 2020  
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <http:##www.gnu.org/licenses/>.
##
##
##-----------------------------------------------------------------------------------------------


:activate_what3words_dialog :en_gb Activate What3Words Dialog
:activate_what3words_dialog_tt :en_gb Activate What3Words Dialog
:activate_what3words_dialog_sh :en_gb Activate What3Words Dialog
:map_extent :en_gb Use Map Extent
:map_extent_tt :en_gb Use Map Extent to limit the suggestions
:map_extent_sh :en_gb Use Map Extent to limit the suggestions
:geocode_address :en_gb Geocode Address
:geocode_address_tt :en_gb Geocode Address
:geocode_address_sh :en_gb Geocode Address
:what3words_address_inspector :en_gb Inspect Address
:what3words_address_inspector_tt :en_gb  Inspect Address, Click on Map
:what3words_address_inspector_sh :en_gb  Inspect Address, Click on Map
:what3word_interaction_mode_prompt :en_gb   Click on a map, results will appear at the selection status bar pane
:what3words_language_chooser :en_gb Choose What3Words Langugae
:what3words_language_chooser_tt :en_gb Choose What3Words Langugae
:what3words_language_chooser_sh :en_gb Choose What3Words Langugae
:geocode_address_search :en_gb Search address
:geocode_address_search_tt :en_gb Search address
:geocode_address_search_sh :en_gb Search address
:previous :en_gb Previous
:next :en_gb Next
:display_grid :en_gb Display What3Words Grid
:display_grid_tt :en_gb Display What3Words Grid
:display_grid_sh :en_gb Display What3Words Grid
:grid_not_supported :en_gb This version of Smallworld doesnt support What3Words Grid

